"""Generates QuestGivers.lua and NPCServices.lua from QuestieDB's Forever NPC data.

QuestGivers.lua lists the NPCs that offer a service with its own cursor
(vendor, repair, trainer, innkeeper, banker, flight master, stable master,
tabard designer) and also start or end quests.

NPCServices.lua gives, for each service NPC, the cursor the game shows for it,
since titles can't tell (a "Bowyer" who also repairs shows the repair anvil),
and the class each class trainer teaches: other classes don't get the trainer
cursor from them.

NPCTitles.lua gives, for the other client languages, the NPC titles that
tell the service cursor (and the class trainer titles), from the translated
NPC data: a title counts when every NPC with it shows the same cursor. It is
the fallback for NPCs new to Forever on non-English clients.

    git clone --depth 1 https://github.com/Questie/QuestieDB.git
    pip install lupa
    python tools/npcData.py <path to QuestieDB>
"""
import os
import subprocess
import sys

from lupa import lua51

HERE = os.path.dirname(os.path.abspath(__file__))
ADDON = os.path.join(HERE, "..")

# npcFlags (QuestieDB src/corrections/enum/expansions.lua)
VENDOR, FLIGHT_MASTER, TRAINER, INNKEEPER, BANKER = 4, 8, 16, 128, 256
TABARD_DESIGNER, STABLEMASTER, REPAIR = 1024, 8192, 16384
SERVICE_FLAGS = VENDOR | FLIGHT_MASTER | TRAINER | INNKEEPER | BANKER | TABARD_DESIGNER | STABLEMASTER | REPAIR

# QuestieDB.npcKeys
NAME, QUEST_STARTS, QUEST_ENDS, SUB_NAME, NPC_FLAGS = 1, 10, 11, 14, 15

CREDIT = """-- NPC IDs derived from the Forever NPC data of QuestieDB (github.com/Questie/QuestieDB,
-- revision {revision}), with thanks to the Questie team. Generated by tools/npcData.py.
local _, ns = ...
"""

QUEST_GIVERS_HEADER = """-- Cursor Glow Forever: NPCs that both offer a service with its own cursor
-- (vendor, repair, trainer, innkeeper, banker, flight master, stable master,
-- tabard designer) and start or end quests. While one of them has a quest for
-- you the game shows the quest cursor, so they start without a service outline
-- until talking to them shows no quests (see isKnownQuestGiver).
--
""" + CREDIT + """
ns.QUEST_GIVER_NPCS = {{
"""

SERVICES_HEADER = """-- Cursor Glow Forever: the cursor the game shows for each service NPC (a
-- HOVER_SHEETS key), from its service flags; titles can't tell, e.g. a
-- "Bowyer" who also repairs shows the repair anvil. NPCs new to Forever are
-- not in the data and fall back to their title.
--
""" + CREDIT + """
ns.NPC_SERVICES = {{
"""

TRAINER_CLASSES_HEADER = """
-- Class trainers (a pet trainer teaches hunters): only their class gets the
-- trainer cursor. Others get the NPC's other service cursor, if any (some
-- also sell), else none. {{class, cursor for other classes}}
ns.TRAINER_CLASSES = {{
"""
TITLE_CLASSES = {
	"Warrior Trainer": "WARRIOR", "Paladin Trainer": "PALADIN", "Hunter Trainer": "HUNTER",
	"Rogue Trainer": "ROGUE", "Priest Trainer": "PRIEST", "Shaman Trainer": "SHAMAN",
	"Mage Trainer": "MAGE", "Warlock Trainer": "WARLOCK", "Druid Trainer": "DRUID",
	"Pet Trainer": "HUNTER", "Portal Trainer": "MAGE",
}


def service_cursor(flags):
	"""The cursor for an NPC's service flags, the more specific service first
	(checked in game: vendor + repair shows the anvil, vendor + innkeeper the
	innkeeper cursor, bankers the bag). Vendor + trainer is left to the title."""
	if flags & REPAIR:
		return "RepairNPC"
	if flags & INNKEEPER:
		return "Innkeeper"
	if flags & FLIGHT_MASTER:
		return "Taxi"
	if flags & STABLEMASTER:
		return "StableMaster"
	if flags & VENDOR and flags & TRAINER:
		return None
	if flags & (BANKER | VENDOR | TABARD_DESIGNER):
		return "Buy"
	if flags & TRAINER:
		return "Trainer"
	return None


def load_npcs(questie_db):
	with open(os.path.join(questie_db, "data", "Forever", "foreverNpcDB.lua"), encoding="utf-8") as f:
		source = f.read()
	start = source.index("QuestieDB.npcData = [[") + len("QuestieDB.npcData = [[")
	return lua51.LuaRuntime().execute(source[start:source.rindex("]]")])


LOCALES = ["deDE", "esES", "esMX", "frFR", "koKR", "ptBR", "ruRU", "zhCN", "zhTW"]

TITLES_HEADER = """-- Cursor Glow Forever: NPC titles on non-English clients, for NPCs not in
-- NPC_SERVICES (new to Forever). TITLE_CURSORS: the cursor for a title (every
-- known NPC with it shows that one); TITLE_TRAINER_CLASSES: the class a class
-- trainer title teaches. Titles are matched whole. English uses the title
-- keywords in CursorGlowForever.lua.
--
""" + CREDIT + """
local locale = GetLocale()
"""


def load_localized(questie_db, locale):
	"""{npc id: translated title} from QuestieDB's Forever translations."""
	with open(os.path.join(questie_db, "l10n", "Forever", "lookupNpcs", locale + ".lua"), encoding="utf-8") as f:
		source = f.read()
	start = source.index("loadstring([[") + len("loadstring([[")
	names = lua51.LuaRuntime().execute(source[start:source.rindex("]]")])
	return {int(npc_id): entry[2] for npc_id, entry in names.items() if entry[2]}


def title_tables(npcs, localized):
	"""Titles every NPC agrees on: {title: cursor} and {title: trainer class}."""
	cursor_votes, class_votes = {}, {}
	for npc_id, npc in npcs.items():
		title = localized.get(int(npc_id))
		if not title:
			continue
		flags = npc[NPC_FLAGS] or 0
		# no service: no cursor of its own; vendor + trainer: can't tell
		cursor = service_cursor(flags) if flags & SERVICE_FLAGS else "none"
		cursor_votes.setdefault(title, set()).add(cursor or "unknown")
		trainer_class = TITLE_CLASSES.get(npc[SUB_NAME])
		class_votes.setdefault(title, set()).add(trainer_class if trainer_class and flags & TRAINER else "none")
	cursors = {t: v.pop() for t, v in cursor_votes.items() if len(v) == 1 and next(iter(v)) not in ("none", "unknown")}
	classes = {t: v.pop() for t, v in class_votes.items() if len(v) == 1 and next(iter(v)) != "none"}
	return cursors, classes


def lua_string(text):
	return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def write_titles(questie_db, revision, npcs):
	with open(os.path.join(ADDON, "NPCTitles.lua"), "w", encoding="utf-8", newline="\n") as f:
		f.write(TITLES_HEADER.format(revision=revision))
		for i, locale in enumerate(LOCALES):
			cursors, classes = title_tables(npcs, load_localized(questie_db, locale))
			f.write('%s locale == "%s" then\n' % ("if" if i == 0 else "elseif", locale))
			f.write("\tns.TITLE_CURSORS = {\n")
			for title in sorted(cursors):
				f.write('\t\t[%s] = "%s",\n' % (lua_string(title), cursors[title]))
			f.write("\t}\n\tns.TITLE_TRAINER_CLASSES = {\n")
			for title in sorted(classes):
				f.write('\t\t[%s] = "%s",\n' % (lua_string(title), classes[title]))
			f.write("\t}\n")
			print(locale, len(cursors), "service titles,", len(classes), "class trainer titles")
		f.write("end\n")


def label(npc):
	return npc[NAME] + (" <%s>" % npc[SUB_NAME] if npc[SUB_NAME] else "")


def write(path, header, revision, rows, more=()):
	with open(os.path.join(ADDON, path), "w", encoding="utf-8", newline="\n") as f:
		f.write(header.format(revision=revision))
		for npc_id, value, text in sorted(rows):
			f.write("\t[%d] = %s, -- %s\n" % (npc_id, value, text))
		f.write("}\n")
		for more_header, more_rows in more:
			f.write(more_header.format())
			for npc_id, value, text in sorted(more_rows):
				f.write("\t[%d] = %s, -- %s\n" % (npc_id, value, text))
			f.write("}\n")
	print("wrote", len(rows), "NPCs to", path)


def main():
	questie_db = sys.argv[1]
	revision = subprocess.run(["git", "-C", questie_db, "log", "-1", "--format=%h"],
		capture_output=True, text=True, check=True).stdout.strip()

	npcs = load_npcs(questie_db)
	quest_givers, services, trainers = [], [], []
	for npc_id, npc in npcs.items():
		flags = npc[NPC_FLAGS] or 0
		if not flags & SERVICE_FLAGS:
			continue
		if npc[QUEST_STARTS] or npc[QUEST_ENDS]:
			quest_givers.append((int(npc_id), "true", label(npc)))
		cursor = service_cursor(flags)
		if cursor:
			services.append((int(npc_id), '"%s"' % cursor, label(npc)))
		trainer_class = TITLE_CLASSES.get(npc[SUB_NAME])
		if trainer_class and flags & TRAINER:
			other = service_cursor(flags & ~TRAINER)
			trainers.append((int(npc_id), '{"%s"%s}' % (trainer_class, ', "%s"' % other if other else ""), label(npc)))

	write("QuestGivers.lua", QUEST_GIVERS_HEADER, revision, quest_givers)
	write("NPCServices.lua", SERVICES_HEADER, revision, services, [(TRAINER_CLASSES_HEADER, trainers)])
	write_titles(questie_db, revision, npcs)


if __name__ == "__main__":
	main()
