"""Generates QuestGivers.lua and NPCServices.lua from QuestieDB's Forever NPC data.

QuestGivers.lua lists the NPCs that offer a service with its own cursor
(vendor, repair, trainer, innkeeper, banker, flight master, stable master,
tabard designer) and also start or end quests.

NPCServices.lua gives, for each service NPC, the cursor the game shows for it,
since titles can't tell (a "Bowyer" who also repairs shows the repair anvil).

    git clone --depth 1 https://github.com/Questie/QuestieDB.git
    pip install lupa
    python tools/npcData.py <path to QuestieDB>
"""
import os
import subprocess
import sys

from lupa import lua51

HERE = os.path.dirname(os.path.abspath(__file__))
ADDON = os.path.join(HERE, "..")

# npcFlags (QuestieDB src/corrections/enum/expansions.lua)
VENDOR, FLIGHT_MASTER, TRAINER, INNKEEPER, BANKER = 4, 8, 16, 128, 256
TABARD_DESIGNER, STABLEMASTER, REPAIR = 1024, 8192, 16384
SERVICE_FLAGS = VENDOR | FLIGHT_MASTER | TRAINER | INNKEEPER | BANKER | TABARD_DESIGNER | STABLEMASTER | REPAIR

# QuestieDB.npcKeys
NAME, QUEST_STARTS, QUEST_ENDS, SUB_NAME, NPC_FLAGS = 1, 10, 11, 14, 15

CREDIT = """-- NPC IDs derived from the Forever NPC data of QuestieDB (github.com/Questie/QuestieDB,
-- revision {revision}), with thanks to the Questie team. Generated by tools/npcData.py.
local _, ns = ...
"""

QUEST_GIVERS_HEADER = """-- Cursor Glow Forever: NPCs that both offer a service with its own cursor
-- (vendor, repair, trainer, innkeeper, banker, flight master, stable master,
-- tabard designer) and start or end quests. While one of them has a quest for
-- you the game shows the quest cursor, so they start without a service outline
-- until talking to them shows no quests (see isKnownQuestGiver).
--
""" + CREDIT + """
ns.QUEST_GIVER_NPCS = {{
"""

SERVICES_HEADER = """-- Cursor Glow Forever: the cursor the game shows for each service NPC (a
-- HOVER_SHEETS key), from its service flags; titles can't tell, e.g. a
-- "Bowyer" who also repairs shows the repair anvil. NPCs new to Forever are
-- not in the data and fall back to their title.
--
""" + CREDIT + """
ns.NPC_SERVICES = {{
"""


def service_cursor(flags):
	"""The cursor for an NPC's service flags, the more specific service first
	(checked in game: vendor + repair shows the anvil, vendor + innkeeper the
	innkeeper cursor, bankers the bag). Vendor + trainer is left to the title."""
	if flags & REPAIR:
		return "RepairNPC"
	if flags & INNKEEPER:
		return "Innkeeper"
	if flags & FLIGHT_MASTER:
		return "Taxi"
	if flags & STABLEMASTER:
		return "StableMaster"
	if flags & VENDOR and flags & TRAINER:
		return None
	if flags & (BANKER | VENDOR | TABARD_DESIGNER):
		return "Buy"
	if flags & TRAINER:
		return "Trainer"
	return None


def load_npcs(questie_db):
	with open(os.path.join(questie_db, "data", "Forever", "foreverNpcDB.lua"), encoding="utf-8") as f:
		source = f.read()
	start = source.index("QuestieDB.npcData = [[") + len("QuestieDB.npcData = [[")
	return lua51.LuaRuntime().execute(source[start:source.rindex("]]")])


def label(npc):
	return npc[NAME] + (" <%s>" % npc[SUB_NAME] if npc[SUB_NAME] else "")


def write(path, header, revision, rows):
	with open(os.path.join(ADDON, path), "w", encoding="utf-8", newline="\n") as f:
		f.write(header.format(revision=revision))
		for npc_id, value, text in sorted(rows):
			f.write("\t[%d] = %s, -- %s\n" % (npc_id, value, text))
		f.write("}\n")
	print("wrote", len(rows), "NPCs to", path)


def main():
	questie_db = sys.argv[1]
	revision = subprocess.run(["git", "-C", questie_db, "log", "-1", "--format=%h"],
		capture_output=True, text=True, check=True).stdout.strip()

	quest_givers, services = [], []
	for npc_id, npc in load_npcs(questie_db).items():
		flags = npc[NPC_FLAGS] or 0
		if not flags & SERVICE_FLAGS:
			continue
		if npc[QUEST_STARTS] or npc[QUEST_ENDS]:
			quest_givers.append((int(npc_id), "true", label(npc)))
		cursor = service_cursor(flags)
		if cursor:
			services.append((int(npc_id), '"%s"' % cursor, label(npc)))

	write("QuestGivers.lua", QUEST_GIVERS_HEADER, revision, quest_givers)
	write("NPCServices.lua", SERVICES_HEADER, revision, services)


if __name__ == "__main__":
	main()
