"""Generates QuestGivers.lua from QuestieDB's Forever NPC data.

Lists the NPCs that offer a service with its own cursor (vendor, repair,
trainer, innkeeper, banker, flight master, stable master, tabard designer) and
also start or end quests.

    git clone --depth 1 https://github.com/Questie/QuestieDB.git
    pip install lupa
    python tools/questGivers.py <path to QuestieDB>
"""
import os
import subprocess
import sys

from lupa import lua51

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "QuestGivers.lua")

# npcFlags (QuestieDB src/corrections/enum/expansions.lua)
VENDOR, FLIGHT_MASTER, TRAINER, INNKEEPER, BANKER = 4, 8, 16, 128, 256
TABARD_DESIGNER, STABLEMASTER, REPAIR = 1024, 8192, 16384
SERVICE_FLAGS = VENDOR | FLIGHT_MASTER | TRAINER | INNKEEPER | BANKER | TABARD_DESIGNER | STABLEMASTER | REPAIR

# QuestieDB.npcKeys
NAME, QUEST_STARTS, QUEST_ENDS, SUB_NAME, NPC_FLAGS = 1, 10, 11, 14, 15

HEADER = """-- Cursor Glow Forever: NPCs that both offer a service with its own cursor
-- (vendor, repair, trainer, innkeeper, banker, flight master, stable master,
-- tabard designer) and start or end quests. While one of them has a quest for
-- you the game shows the quest cursor, so they start without a service outline
-- until talking to them shows no quests (see isKnownQuestGiver).
--
-- NPC IDs derived from the Forever NPC data of QuestieDB (github.com/Questie/QuestieDB,
-- revision {revision}), with thanks to the Questie team. Generated by tools/questGivers.py.
local _, ns = ...

ns.QUEST_GIVER_NPCS = {{
"""


def load_npcs(questie_db):
	with open(os.path.join(questie_db, "data", "Forever", "foreverNpcDB.lua"), encoding="utf-8") as f:
		source = f.read()
	start = source.index("QuestieDB.npcData = [[") + len("QuestieDB.npcData = [[")
	return lua51.LuaRuntime().execute(source[start:source.rindex("]]")])


def main():
	questie_db = sys.argv[1]
	revision = subprocess.run(["git", "-C", questie_db, "log", "-1", "--format=%h"],
		capture_output=True, text=True, check=True).stdout.strip()

	rows = []
	for npc_id, npc in load_npcs(questie_db).items():
		has_quests = npc[QUEST_STARTS] or npc[QUEST_ENDS]
		if (npc[NPC_FLAGS] or 0) & SERVICE_FLAGS and has_quests:
			label = npc[NAME] + (" <%s>" % npc[SUB_NAME] if npc[SUB_NAME] else "")
			rows.append((int(npc_id), label))

	with open(OUT, "w", encoding="utf-8", newline="\n") as f:
		f.write(HEADER.format(revision=revision))
		for npc_id, label in sorted(rows):
			f.write("\t[%d] = true, -- %s\n" % (npc_id, label))
		f.write("}\n")
	print("wrote", len(rows), "NPCs to", os.path.normpath(OUT))


if __name__ == "__main__":
	main()
